const vocabularyData = {
    1: [
        {word: "ant", type: "n.", meaning: "มด"},
        {word: "apple", type: "n.", meaning: "แอปเปิ้ล"},
        {word: "bag", type: "n.", meaning: "กระเป๋า,ย่าม"},
        {word: "ball", type: "n.", meaning: "ลูกบอล"},
        {word: "banana", type: "n.", meaning: "กล้วย"},
        {word: "bat", type: "n.", meaning: "ค้างคาว"},
        {word: "bean", type: "n.", meaning: "ต้นถั่ว,ฝักถั่ว"},
        {word: "bear", type: "n.", meaning: "หมี"},
        {word: "bee", type: "n.", meaning: "ผึ้ง"},
        {word: "big", type: "adj.", meaning: "ใหญ่"},
        {word: "bin", type: "n.", meaning: "ถังขยะ"},
        {word: "bird", type: "n.", meaning: "นก"},
        {word: "birthday", type: "n.", meaning: "วันเกิด"},
        {word: "book", type: "n.", meaning: "หนังสือ"},
        {word: "box", type: "n.", meaning: "กล่อง"},
        {word: "boy", type: "n.", meaning: "เด็กผู้ชาย"},
        {word: "bread", type: "n.", meaning: "ขนมปัง"},
        {word: "broom", type: "n.", meaning: "ไม้กวาด"},
        {word: "brother", type: "n.", meaning: "พี่ชาย,น้องชาย"},
        {word: "bus", type: "n.", meaning: "รถประจำทาง"},
        {word: "cake", type: "n.", meaning: "ขนมเค้ก"},
        {word: "candle", type: "n.", meaning: "เทียนไข"},
        {word: "car", type: "n.", meaning: "รถยนต์"},
        {word: "cat", type: "n.", meaning: "แมว"},
        {word: "chair", type: "n.", meaning: "เก้าอี้"},
        {word: "class", type: "n.", meaning: "ชั้นเรียน"},
        {word: "close", type: "v.", meaning: "ปิด"},
        {word: "count", type: "v.", meaning: "นับ"},
        {word: "cry", type: "v.", meaning: "ร้องไห้"},
        {word: "crayon", type: "n.", meaning: "สีเทียน"},
        {word: "cup", type: "n.", meaning: "ถ้วยกาแฟ"},
        {word: "cut", type: "v.", meaning: "ตัด"},
        {word: "dad", type: "n.", meaning: "พ่อ"},
        {word: "dance", type: "v.", meaning: "เต้นรำ"},
        {word: "desk", type: "n.", meaning: "โต๊ะเรียน"},
        {word: "dog", type: "n.", meaning: "สุนัข"},
        {word: "door", type: "n.", meaning: "ประตู"},
        {word: "dot", type: "n.", meaning: "จุด"},
        {word: "ear", type: "n.", meaning: "หู"},
        {word: "egg", type: "n.", meaning: "ไข่"},
        {word: "eraser", type: "n.", meaning: "ยางลบ"},
        {word: "eye", type: "n.", meaning: "ตา"},
        {word: "face", type: "n.", meaning: "หน้า,ใบหน้า"},
        {word: "fan", type: "n.", meaning: "พัดลม"},
        {word: "farm", type: "n.", meaning: "ไร่นา,ฟาร์ม"},
        {word: "farmer", type: "n.", meaning: "ชาวนา"},
        {word: "father", type: "n.", meaning: "บิดา"},
        {word: "fish", type: "n.", meaning: "ปลา"},
        {word: "flower", type: "n.", meaning: "ดอกไม้"},
        {word: "food", type: "n.", meaning: "อาหาร"},
        {word: "foot", type: "n.", meaning: "เท้า"},
        {word: "fox", type: "n.", meaning: "สุนัขจิ้งจอก"},
        {word: "fruit", type: "n.", meaning: "ผลไม้"},
        {word: "fun", type: "n.", meaning: "ความสนุกสนาน"},
        {word: "giraffe", type: "n.", meaning: "ยีราฟ"},
        {word: "girl", type: "n.", meaning: "เด็กผู้หญิง"},
        {word: "glass", type: "n.", meaning: "แก้วน้ำ"},
        {word: "go", type: "v.", meaning: "ไป"},
        {word: "goat", type: "n.", meaning: "แพะ"},
        {word: "good", type: "adj.", meaning: "ดี"},
        {word: "goodbye", type: "interj.", meaning: "ลาก่อน"},
        {word: "hair", type: "n.", meaning: "ผม"},
        {word: "ham", type: "n.", meaning: "เนื้อขาหมูรมควัน"},
        {word: "happy", type: "adj.", meaning: "มีความสุข"},
        {word: "head", type: "n.", meaning: "ศีรษะ"},
        {word: "hello", type: "interj.", meaning: "สวัสดี"},
        {word: "house", type: "n.", meaning: "บ้าน"},
        {word: "ice", type: "n.", meaning: "น้ำแข็ง"},
        {word: "ice cream", type: "n.", meaning: "ไอศกรีม"},
        {word: "jar", type: "n.", meaning: "โอ่ง"},
        {word: "key", type: "n.", meaning: "ลูกกุญแจ"},
        {word: "kick", type: "v.", meaning: "เตะ"},
        {word: "king", type: "n.", meaning: "พระราชา"},
        {word: "kid", type: "n.", meaning: "เด็ก"},
        {word: "leg", type: "n.", meaning: "ขา"},
        {word: "lemon", type: "n.", meaning: "มะนาว"},
        {word: "line", type: "n.", meaning: "เส้น,บรรทัด"},
        {word: "lion", type: "n.", meaning: "สิงโต"},
        {word: "listen", type: "v.", meaning: "ฟัง"},
        {word: "long", type: "adj.", meaning: "ยาว"},
        {word: "look", type: "v.", meaning: "ดู,มองดู"},
        {word: "love", type: "v.", meaning: "รัก"},
        {word: "meet", type: "v.", meaning: "พบ, เจอ"},
        {word: "man", type: "n.", meaning: "ผู้ชาย"},
        {word: "map", type: "n.", meaning: "แผนที่"},
        {word: "milk", type: "n.", meaning: "นม"},
        {word: "mom", type: "n.", meaning: "แม่"},
        {word: "monkey", type: "n.", meaning: "ลิง"},
        {word: "moon", type: "n.", meaning: "ดวงจันทร์"},
        {word: "mother", type: "n.", meaning: "มารดา"},
        {word: "mouth", type: "n.", meaning: "ปาก"},
        {word: "name", type: "n.", meaning: "ชื่อ"},
        {word: "nose", type: "n.", meaning: "จมูก"},
        {word: "open", type: "v.", meaning: "เปิด"},
        {word: "orange", type: "n.", meaning: "ส้ม"},
        {word: "owl", type: "n.", meaning: "นกฮูก"},
        {word: "pan", type: "n.", meaning: "กระทะ"},
        {word: "panda", type: "n.", meaning: "หมีแพนด้า"},
        {word: "papaya", type: "n.", meaning: "มะละกอ"},
        {word: "park", type: "n.", meaning: "สวนสาธารณะ"},
        {word: "pear", type: "n.", meaning: "ลูกแพร์"},
        {word: "pen", type: "n.", meaning: "ปากกา"},
        {word: "pencil", type: "n.", meaning: "ดินสอ"},
        {word: "pet", type: "n.", meaning: "สัตว์เลี้ยง"},
        {word: "play", type: "v.", meaning: "เล่น"},
        {word: "point", type: "v./n.", meaning: "ชี้, คะแนน, จุด"},
        {word: "pool", type: "n.", meaning: "สระน้ำ"},
        {word: "queen", type: "n.", meaning: "ราชินี"},
        {word: "rabbit", type: "n.", meaning: "กระต่าย"},
        {word: "rat", type: "n.", meaning: "หนู"},
        {word: "ring", type: "n.", meaning: "แหวน"},
        {word: "roof", type: "n.", meaning: "หลังคา"},
        {word: "room", type: "n.", meaning: "ห้อง"},
        {word: "ruler", type: "n.", meaning: "ไม้บรรทัด"},
        {word: "sad", type: "adj.", meaning: "เศร้า"},
        {word: "salad", type: "n.", meaning: "สลัดผัก"},
        {word: "say", type: "v.", meaning: "พูด"},
        {word: "school", type: "n.", meaning: "โรงเรียน"},
        {word: "see", type: "v.", meaning: "เห็น"},
        {word: "sheep", type: "n.", meaning: "แกะ"},
        {word: "ship", type: "n.", meaning: "เรือ"},
        {word: "short", type: "adj.", meaning: "สั้น,เตี้ย"},
        {word: "show", type: "v.", meaning: "แสดง"},
        {word: "sing", type: "v.", meaning: "ร้องเพลง"},
        {word: "sister", type: "n.", meaning: "พี่สาว,น้องสาว"},
        {word: "sit", type: "v.", meaning: "นั่ง"},
        {word: "small", type: "adj.", meaning: "เล็ก"},
        {word: "smell", type: "v.", meaning: "ได้กลิ่น,ดมกลิ่น"},
        {word: "snake", type: "n.", meaning: "งู"},
        {word: "song", type: "n.", meaning: "เพลง"},
        {word: "stand", type: "v.", meaning: "ยืน"},
        {word: "star", type: "n.", meaning: "ดวงดาว"},
        {word: "start", type: "v.", meaning: "เริ่ม"},
        {word: "stop", type: "v.", meaning: "หยุด"},
        {word: "student", type: "n.", meaning: "นักเรียน"},
        {word: "sun", type: "n.", meaning: "ดวงอาทิตย์"},
        {word: "swim", type: "v.", meaning: "ว่ายน้ำ"},
        {word: "T.V.", type: "n.", meaning: "โทรทัศน์"},
        {word: "table", type: "n.", meaning: "โต๊ะ"},
        {word: "tall", type: "adj.", meaning: "สูง"},
        {word: "tea", type: "n.", meaning: "น้ำชา"},
        {word: "teacher", type: "n.", meaning: "ครู"},
        {word: "thank you", type: "n.", meaning: "การแสดงความขอบคุณ"},
        {word: "tomato", type: "n.", meaning: "มะเขือเทศ"},
        {word: "top", type: "n.", meaning: "ลูกข่าง"},
        {word: "toy", type: "n.", meaning: "ของเล่น"},
        {word: "tree", type: "n.", meaning: "ต้นไม้"},
        {word: "ugly", type: "adj.", meaning: "น่าเกลียด"},
        {word: "van", type: "n.", meaning: "รถตู้"},
        {word: "walk", type: "v.", meaning: "เดิน"},
        {word: "water", type: "n.", meaning: "น้ำ"},
        {word: "wig", type: "n.", meaning: "ผมปลอม"},
        {word: "woman", type: "n.", meaning: "ผู้หญิง"},
        {word: "zebra", type: "n.", meaning: "ม้าลาย"},
        {word: "zoo", type: "n.", meaning: "สวนสัตว์"}
    ],
    2: [
        {word: "again", type: "adv.", meaning: "อีกครั้ง"},
        {word: "alphabet", type: "n.", meaning: "พยัญชนะ"},
        {word: "animal", type: "n.", meaning: "สัตว์"},
        {word: "answer", type: "n.", meaning: "การตอบคำถาม, คำตอบ"},
        {word: "arm", type: "n.", meaning: "แขน"},
        {word: "artist", type: "n.", meaning: "ศิลปิน"},
        {word: "ask", type: "v.", meaning: "ถาม"},
        {word: "aunt", type: "n.", meaning: "ป้า"},
        {word: "bakery", type: "n.", meaning: "ร้านขายขนมอบ"},
        {word: "balloon", type: "n.", meaning: "ลูกโป่ง"},
        {word: "bank", type: "n.", meaning: "ธนาคาร"},
        {word: "bed", type: "n.", meaning: "เตียงนอน"},
        {word: "board", type: "n.", meaning: "กระดาน"},
        {word: "boat", type: "n.", meaning: "เรือ"},
        {word: "boots", type: "n.", meaning: "รองเท้าหุ้มข้อหรือหุ้มขา"},
        {word: "bottle", type: "n.", meaning: "ขวด"},
        {word: "bowl", type: "n.", meaning: "ชาม"},
        {word: "butterfly", type: "n.", meaning: "ผีเสื้อ"},
        {word: "can", type: "n., v.", meaning: "กระป๋อง. สามารถ"},
        {word: "candy", type: "n.", meaning: "ลูกอม"},
        {word: "cap", type: "n.", meaning: "หมวกแก็ป"},
        {word: "card", type: "n.", meaning: "บัตรอวยพร"},
        {word: "chant", type: "n.", meaning: "บทพูดเข้าจังหวะ"},
        {word: "chat", type: "v.", meaning: "คุยเล่น"},
        {word: "check", type: "v., n.", meaning: "ตรวจสอบ, การตรวจสอบ"},
        {word: "cheese", type: "n.", meaning: "เนยแข็ง"},
        {word: "cherry", type: "n.", meaning: "ผลเชอร์รี่"},
        {word: "chicken", type: "n.", meaning: "ไก่, เนื้อไก่"},
        {word: "children", type: "n.", meaning: "เด็กหลายคน"},
        {word: "chilli", type: "n.", meaning: "พริก"},
        {word: "chip", type: "n.", meaning: "แผ่นมันฝรั่งทอดกรอบ"},
        {word: "circle", type: "n.", meaning: "วงกลม"},
        {word: "clap", type: "v.", meaning: "ปรบมือ"},
        {word: "clean", type: "adj.", meaning: "สะอาด"},
        {word: "clock", type: "n.", meaning: "นาฬิกาติดผนัง"},
        {word: "cook", type: "v.", meaning: "ปรุงหรือทำอาหาร"},
        {word: "cookie", type: "n.", meaning: "ขนมอบ"},
        {word: "cool", type: "adj.", meaning: "เย็น"},
        {word: "cow", type: "n.", meaning: "วัวตัวเมีย"},
        {word: "dish", type: "n.", meaning: "จาน"},
        {word: "donkey", type: "n.", meaning: "ลา"},
        {word: "elephant", type: "n.", meaning: "ช้าง"},
        {word: "enjoy", type: "v.", meaning: "สนุกสนาน"},
        {word: "family", type: "n.", meaning: "ครอบครัว"},
        {word: "far", type: "adv.", meaning: "ไกล"},
        {word: "fat", type: "adj.", meaning: "อ้วน"},
        {word: "favorite", type: "adj.", meaning: "เป็นที่ชื่นชอบ"},
        {word: "fin", type: "n.", meaning: "ครีบ"},
        {word: "fine", type: "adj., n.", meaning: "ดี, ค่าปรับ"},
        {word: "finish", type: "v.", meaning: "เสร็จ, สำเร็จ"},
        {word: "floor", type: "n.", meaning: "พื้นห้อง, ชั้นของตึก"},
        {word: "fly", type: "v.", meaning: "บิน"},
        {word: "friend", type: "n.", meaning: "เพื่อน"},
        {word: "frog", type: "n.", meaning: "กบ"},
        {word: "gate", type: "n.", meaning: "ประตู"},
        {word: "get up", type: "v.", meaning: "ตื่น"},
        {word: "gloves", type: "n.", meaning: "ถุงมือ"},
        {word: "glue", type: "n.", meaning: "กาว"},
        {word: "grandma", type: "n", meaning: "คุณย่าหรือคุณยาย"},
        {word: "grandpa", type: "n", meaning: "คุณปู่หรือคุณตา"},
        {word: "grape", type: "n.", meaning: "องุ่น"},
        {word: "group", type: "n.", meaning: "กลุ่ม"},
        {word: "gum", type: "n.", meaning: "หมากฝรั่ง"},
        {word: "hand", type: "n.", meaning: "มือ"},
        {word: "hat", type: "n.", meaning: "หมวก"},
        {word: "help", type: "v.", meaning: "ช่วยเหลือ"},
        {word: "hen", type: "n.", meaning: "แม่ไก่"},
        {word: "hide", type: "v.", meaning: "แอบ, ซ่อน"},
        {word: "hot", type: "adj.", meaning: "ร้อน"},
        {word: "hot dog", type: "n", meaning: "ไส้กรอกร้อนๆที่ประกบด้วยขนมปัง"},
        {word: "hungry", type: "adj.", meaning: "หิวกระหาย"},
        {word: "idea", type: "n.", meaning: "ความนึกคิด, ความคิดเห็น"},
        {word: "jam", type: "n.", meaning: "แยม, ผลไม้กวนกับน้ำตาล"},
        {word: "job", type: "n.", meaning: "งาน, อาชีพ"},
        {word: "jug", type: "n.", meaning: "เหยือก"},
        {word: "kite", type: "n.", meaning: "ว่าว"},
        {word: "knee", type: "n.", meaning: "หัวเข่า"},
        {word: "knife", type: "n.", meaning: "มีด"},
        {word: "lady", type: "n.", meaning: "ผู้หญิง สุภาพสตรี"},
        {word: "left", type: "adj.", meaning: "ข้างซ้าย"},
        {word: "letter", type: "n.", meaning: "จดหมาย"},
        {word: "like", type: "v.", meaning: "ชื่นชอบ"},
        {word: "magic", type: "n.", meaning: "มายากล, เวทย์มนต์"},
        {word: "make", type: "v.", meaning: "ทำ"},
        {word: "mango", type: "n.", meaning: "มะม่วง"},
        {word: "match", type: "n.", meaning: "การเข้าชุดกัน"},
        {word: "music", type: "n.", meaning: "ดนตรี"},
        {word: "new", type: "adj.", meaning: "ใหม่ สด แปลก"},
        {word: "notebook", type: "n.", meaning: "สมุดบันทึก"},
        {word: "number", type: "n.", meaning: "จำนวน, หมายเลข"},
        {word: "old", type: "adj.", meaning: "แก่, ชรา"},
        {word: "page", type: "n.", meaning: "หน้าหนังสือ"},
        {word: "paint", type: "v.", meaning: "ระบายสี"},
        {word: "paper", type: "n.", meaning: "แผ่นกระดาษ"},
        {word: "pea", type: "n.", meaning: "ถั่ว"},
        {word: "peach", type: "n.", meaning: "ลูกพีช"},
        {word: "pencil case", type: "n.", meaning: "กล่องดินสอ"},
        {word: "people", type: "n.", meaning: "คน, ประชาชน"},
        {word: "person", type: "n.", meaning: "คน, บุคคล"},
        {word: "pick", type: "v.", meaning: "เลือก, หยิบ, จับ"},
        {word: "picture", type: "n.", meaning: "รูปภาพ"},
        {word: "pig", type: "n.", meaning: "หมู"},
        {word: "pillow", type: "n.", meaning: "หมอน"},
        {word: "pineapple", type: "n.", meaning: "สับประรด"},
        {word: "place", type: "n.", meaning: "สถานที่"},
        {word: "puppy", type: "n.", meaning: "ลูกสุนัข"},
        {word: "put", type: "v.", meaning: "วาง, ตั้ง"},
        {word: "quiet", type: "adj.", meaning: "เงียบ"},
        {word: "race", type: "n.", meaning: "การแข่งด้านความเร็ว"},
        {word: "radio", type: "n.", meaning: "วิทยุ"},
        {word: "rain", type: "n.", meaning: "ฝน"},
        {word: "ready", type: "adj.", meaning: "พร้อม, พร้อมแล้ว"},
        {word: "relax", type: "v.", meaning: "รู้สึกผ่อนคลาย"},
        {word: "replace", type: "v.", meaning: "เปลี่ยนที่, แทนที่"},
        {word: "rice", type: "n.", meaning: "ข้าว"},
        {word: "right", type: "adj.", meaning: "ความถูกต้อง"},
        {word: "robot", type: "n.", meaning: "หุ่นยนต์"},
        {word: "rock", type: "n.", meaning: "หิน, โขดหิน"},
        {word: "rope", type: "n.", meaning: "เชือก, บ่วง"},
        {word: "round", type: "adj.", meaning: "กลม, เป็นวงกลม"},
        {word: "run", type: "v.", meaning: "วิ่ง"},
        {word: "sandals", type: "n.", meaning: "รองเท้าสาน, รองเท้าที่มีสายรัด"},
        {word: "sandwich", type: "n.", meaning: "ขนมปังแซนด์วิช"},
        {word: "scooter", type: "n.", meaning: "ยานยนต์แบบจักรยานขนาดเล็ก"},
        {word: "shark", type: "n.", meaning: "ฉลาม"},
        {word: "shirt", type: "n.", meaning: "เสื้อเชิ้ต"},
        {word: "shoes", type: "n.", meaning: "รองเท้า"},
        {word: "sit down", type: "v.", meaning: "นั่งลง"},
        {word: "skirt", type: "n.", meaning: "กระโปรง"},
        {word: "socks", type: "n.", meaning: "ถุงเท้า"},
        {word: "sorry", type: "adj.", meaning: "ขอโทษ, ขออภัย"},
        {word: "spell", type: "v.", meaning: "สะกด"},
        {word: "stamp", type: "n.", meaning: "ดวงตราไปรษณียากร"},
        {word: "stand up", type: "v.", meaning: "ยืนขึ้น"},
        {word: "store", type: "n.", meaning: "ร้านค้า, คลังสินค้า"},
        {word: "story", type: "n.", meaning: "เรื่องราว, เรื่องเล่า"},
        {word: "strawberry", type: "n.", meaning: "ผลสตรอเบอร์รี่"},
        {word: "subject", type: "n.", meaning: "วิชา"},
        {word: "tell", type: "v.", meaning: "บอก"},
        {word: "tennis", type: "n.", meaning: "กีฬาเทนนิส"},
        {word: "thumb", type: "n.", meaning: "นิ้วหัวแม่มือ"},
        {word: "today", type: "n.", meaning: "วันนี้"},
        {word: "toe", type: "n.", meaning: "นิ้วเท้า"},
        {word: "touch", type: "v.", meaning: "สัมผัส"},
        {word: "town", type: "n.", meaning: "เมือง, ชุมชน"},
        {word: "T-shirt", type: "n.", meaning: "เสื้อยืดคอกลม"},
        {word: "umbrella", type: "n.", meaning: "ร่ม"},
        {word: "uncle", type: "n.", meaning: "ลุง"},
        {word: "video", type: "n.", meaning: "วีดีทัศน์"},
        {word: "walk", type: "v.", meaning: "เดิน"},
        {word: "watermelon", type: "n.", meaning: "แตงโม"},
        {word: "week", type: "n.", meaning: "สัปดาห์"},
        {word: "weekend", type: "n.", meaning: "วันหยุดสุดสัปดาห์"},
        {word: "welcome", type: "adj.", meaning: "ซึ่งต้อนรับด้วยความยินดี"},
        {word: "whale", type: "n.", meaning: "วาฬ"},
        {word: "window", type: "n.", meaning: "หน้าต่าง"},
        {word: "worm", type: "n.", meaning: "หนอน"},
        {word: "young", type: "adj.", meaning: "อ่อน, อายุน้อย"},
        {word: "yourself", type: "pron.", meaning: "ตัวของเธอเอง"}
    ],
    3: [
        {word: "act", type: "n.", meaning: "การแสดง,การกระทำ"},
        {word: "air", type: "n.", meaning: "อากาศ"},
        {word: "airplane", type: "n.", meaning: "เครื่องบิน"},
        {word: "around", type: "adv.", meaning: "โดยรอบ,รอบด้าน"},
        {word: "art", type: "n.", meaning: "ศิลปะ"},
        {word: "basket", type: "n.", meaning: "ตะกร้า"},
        {word: "bathroom", type: "n.", meaning: "ห้องน้ำ"},
        {word: "beautiful", type: "adj.", meaning: "สวย"},
        {word: "bedroom", type: "n.", meaning: "ห้องนอน"},
        {word: "beef", type: "n.", meaning: "เนื้อวัว"},
        {word: "bell", type: "n.", meaning: "กระดิ่ง,ระฆัง"},
        {word: "bicycle", type: "n.", meaning: "รถจักรยาน"},
        {word: "bike", type: "n.", meaning: "รถจักรยาน"},
        {word: "blackboard", type: "n.", meaning: "กระดานดำ"},
        {word: "blank", type: "adj.", meaning: "ว่าง ,ว่างเปล่า"},
        {word: "body", type: "n.", meaning: "ร่างกาย"},
        {word: "bookcase", type: "n.", meaning: "ชั้นหนังสือ"},
        {word: "borrow", type: "v.", meaning: "ขอยืม"},
        {word: "bottom", type: "n.", meaning: "ก้น"},
        {word: "breakfast", type: "n.", meaning: "อาหารมื้อเช้า"},
        {word: "bug", type: "n.", meaning: "แมลงปีกแข็ง"},
        {word: "buy", type: "v.", meaning: "ซื้อ"},
        {word: "cabbage", type: "n.", meaning: "กะหล่ำปลี"},
        {word: "carrot", type: "n.", meaning: "แครรอท"},
        {word: "castle", type: "n.", meaning: "ปราสาท"},
        {word: "chalk", type: "n.", meaning: "ชอล์ก"},
        {word: "chance", type: "n.", meaning: "โอกาส,โชค"},
        {word: "change", type: "v.", meaning: "เปลี่ยน,สลับ"},
        {word: "classroom", type: "n.", meaning: "ห้องเรียน"},
        {word: "coffee", type: "n.", meaning: "กาแฟ"},
        {word: "computer", type: "n.", meaning: "คอมพิวเตอร์"},
        {word: "correct", type: "adj.", meaning: "ถูกต้อง"},
        {word: "cross", type: "n.", meaning: "เครื่องหมายกากบาท"},
        {word: "cucumber", type: "n.", meaning: "แตงกวา"},
        {word: "daughter", type: "n.", meaning: "ลูกสาว"},
        {word: "dice", type: "n.", meaning: "ลูกเต๋า"},
        {word: "dinner", type: "n.", meaning: "อาหารมื้อเย็น"},
        {word: "dirty", type: "adj.", meaning: "สกปรก"},
        {word: "doctor", type: "n.", meaning: "แพทย์"},
        {word: "double", type: "adj.", meaning: "เป็นสองเท่า"},
        {word: "drink", type: "v.", meaning: "ดื่ม"},
        {word: "drum", type: "n.", meaning: "กลอง"},
        {word: "duck", type: "n.", meaning: "เป็ด"},
        {word: "durian", type: "n.", meaning: "ทุเรียน"},
        {word: "eat", type: "v.", meaning: "กิน,รับประทาน"},
        {word: "English", type: "n.", meaning: "ภาษาอังกฤษ"},
        {word: "false", type: "adj.", meaning: "ผิด,ไม่ถูกต้อง"},
        {word: "finger", type: "n.", meaning: "นิ้วมือ"},
        {word: "fishing", type: "n.", meaning: "กีฬาตกปลา"},
        {word: "flag", type: "n.", meaning: "ธง"},
        {word: "garden", type: "n.", meaning: "สวน,สนามหญ้า"},
        {word: "give", type: "v.", meaning: "ให้"},
        {word: "goldfish", type: "n.", meaning: "ปลาทอง"},
        {word: "golf", type: "n.", meaning: "กีฬากอล์ฟ"},
        {word: "goose", type: "n.", meaning: "ห่าน"},
        {word: "grandfather", type: "n.", meaning: "ปู่,ตา"},
        {word: "grandmother", type: "n.", meaning: "ย่า,ยาย"},
        {word: "grass", type: "n.", meaning: "หญ้า"},
        {word: "great", type: "adj.", meaning: "ยิ่งใหญ่"},
        {word: "guitar", type: "n.", meaning: "กีตาร์"},
        {word: "gun", type: "n.", meaning: "ปืน"},
        {word: "hippo", type: "n.", meaning: "ฮิบโปโปเตมัส"},
        {word: "hit", type: "v.", meaning: "ตี"},
        {word: "hold", type: "v.", meaning: "ถือ,จับ"},
        {word: "homework", type: "n.", meaning: "การบ้าน"},
        {word: "honey", type: "n.", meaning: "น้ำผึ้ง"},
        {word: "hop", type: "v.", meaning: "กระโดด"},
        {word: "horse", type: "n.", meaning: "ม้า"},
        {word: "hut", type: "n.", meaning: "กระท่อม"},
        {word: "ink", type: "n.", meaning: "หมึก น้ำหมึก"},
        {word: "jacket", type: "n.", meaning: "เสื้อแจ็กแก็ต"},
        {word: "jeans", type: "n.", meaning: "กางเกงยีนส์"},
        {word: "join", type: "v.", meaning: "เข้าด้วยกัน"},
        {word: "juice", type: "n.", meaning: "น้ำผลไม้"},
        {word: "keep", type: "v.", meaning: "เก็บรักษา"},
        {word: "kitten", type: "n.", meaning: "ลูกแมว"},
        {word: "living-room", type: "n.", meaning: "ห้องนั่งเล่น"},
        {word: "lock", type: "n.", meaning: "กุญแจ แม่กุญแจ"},
        {word: "log", type: "n.", meaning: "ซุง ท่อนซุง"},
        {word: "lunch", type: "n.", meaning: "อาหารมื้อกลางวัน"},
        {word: "math", type: "n.", meaning: "วิชาคณิตศาสตร์"},
        {word: "meat", type: "n.", meaning: "เนื้อสัตว์"},
        {word: "mirror", type: "n.", meaning: "กระจก"},
        {word: "month", type: "n.", meaning: "เดือน"},
        {word: "mop", type: "n.", meaning: "ไม้ถูพื้น"},
        {word: "move", type: "v.", meaning: "ย้าย เคลื่อนย้าย เคลื่อนที่"},
        {word: "musician", type: "n.", meaning: "นักดนตรี"},
        {word: "neck", type: "n.", meaning: "คอ"},
        {word: "nest", type: "n.", meaning: "รัง"},
        {word: "noodle", type: "n.", meaning: "ก๋วยเตี๋ยว"},
        {word: "noon", type: "n.", meaning: "เที่ยงวัน"},
        {word: "nurse", type: "n.", meaning: "นางพยาบาล"},
        {word: "ox", type: "n.", meaning: "วัวตัวผู้"},
        {word: "pair", type: "n.", meaning: "คู่"},
        {word: "parrot", type: "n.", meaning: "นกแก้ว"},
        {word: "path", type: "n.", meaning: "ทางเดิน"},
        {word: "penguin", type: "n.", meaning: "นกเพนกวิน"},
        {word: "photo", type: "n.", meaning: "รูปภาพ"},
        {word: "piano", type: "n.", meaning: "เปียโน"},
        {word: "pie", type: "n.", meaning: "ขนมพาย"},
        {word: "pizza", type: "n.", meaning: "พิซซ่า"},
        {word: "plastic", type: "n.", meaning: "พลาสติก"},
        {word: "pomelo", type: "n.", meaning: "ส้มโอ"},
        {word: "pork", type: "n.", meaning: "เนื้อหมู"},
        {word: "postman", type: "n.", meaning: "บุรุษไปรษณีย์"},
        {word: "potato", type: "n.", meaning: "มันฝรั่ง"},
        {word: "question", type: "n.", meaning: "คำถาม"},
        {word: "rainy", type: "adj.", meaning: "ฝนตกชุก"},
        {word: "reach", type: "v.", meaning: "ไปถึง,เข้าถึง"},
        {word: "read", type: "v.", meaning: "อ่าน"},
        {word: "river", type: "n.", meaning: "แม่น้ำ"},
        {word: "salt", type: "n.", meaning: "เกลือ"},
        {word: "sand", type: "n.", meaning: "ทราย"},
        {word: "sauce", type: "n.", meaning: "น้ำจิ้ม"},
        {word: "sausage", type: "n.", meaning: "ไส้กรอก"},
        {word: "seal", type: "n.", meaning: "แมวน้ำ"},
        {word: "shampoo", type: "n.", meaning: "ยาสระผม"},
        {word: "sharpener", type: "n.", meaning: "กบเหลาดินสอ"},
        {word: "shorts", type: "n.", meaning: "กางเกงขาสั้น"},
        {word: "shoulder", type: "n.", meaning: "หัวไหล่"},
        {word: "skate", type: "n.", meaning: "สเก็ต"},
        {word: "sleep", type: "v.", meaning: "นอนหลับ"},
        {word: "slide", type: "v.", meaning: "ลื่นไถล,ไถล"},
        {word: "smile", type: "v.", meaning: "ยิ้ม"},
        {word: "snail", type: "n.", meaning: "หอยทาก"},
        {word: "soap", type: "n.", meaning: "สบู่"},
        {word: "sofa", type: "n.", meaning: "โซฟา"},
        {word: "soldier", type: "n.", meaning: "ทหาร"},
        {word: "son", type: "n.", meaning: "ลูกชาย"},
        {word: "soup", type: "n.", meaning: "น้ำแกง"},
        {word: "speak", type: "v.", meaning: "พูด"},
        {word: "stick", type: "n.", meaning: "กิ่งไม้,ก้านไม้"},
        {word: "study", type: "v.", meaning: "เรียน"},
        {word: "sweet", type: "adj.", meaning: "หวาน"},
        {word: "swing", type: "n.", meaning: "ชิงช้า"},
        {word: "telephone", type: "n.", meaning: "โทรศัพท์"},
        {word: "thirsty", type: "adj.", meaning: "กระหาย"},
        {word: "tiger", type: "n.", meaning: "เสือ"},
        {word: "toothbrush", type: "n.", meaning: "แปรงสีฟัน"},
        {word: "toothpaste", type: "n.", meaning: "ยาสีฟัน"},
        {word: "tortoise", type: "n.", meaning: "เต่า"},
        {word: "truck", type: "n.", meaning: "รถบรรทุก"},
        {word: "true", type: "adj.", meaning: "จริง ,ถูก"},
        {word: "turtle", type: "n.", meaning: "เต่าทะเล"},
        {word: "use", type: "v.", meaning: "ใช้"},
        {word: "violin", type: "n.", meaning: "ไวโอลิน"},
        {word: "want", type: "v.", meaning: "ต้องการ"},
        {word: "wash", type: "v.", meaning: "ซักล้าง"},
        {word: "watch", type: "n.", meaning: "นาฬิกาข้อมือ"},
        {word: "wing", type: "n.", meaning: "ปีก"},
        {word: "wolf", type: "n.", meaning: "หมาป่า"},
        {word: "wood", type: "n.", meaning: "ไม้"},
        {word: "write", type: "v.", meaning: "เขียน"},
        {word: "wrong", type: "adj.", meaning: "ผิด"}
    ],
    4: [
        {word: "ache", type: "n.", meaning: "อาการปวด"},
        {word: "afternoon", type: "n.", meaning: "เวลาบ่าย"},
        {word: "airport", type: "n.", meaning: "สนามบิน"},
        {word: "autumn", type: "n.", meaning: "ฤดูใบไม้ร่วง"},
        {word: "awake", type: "v.", meaning: "ตื่นนอน"},
        {word: "baht", type: "n.", meaning: "หน่วยเงินตราของไทย"},
        {word: "bamboo", type: "n.", meaning: "ต้นไผ่, ไม้ไผ่"},
        {word: "barbecue", type: "n.", meaning: "เตาย่างอาหารกลางแจ้ง"},
        {word: "beak", type: "n.", meaning: "จงอยปากนก"},
        {word: "beverage", type: "n.", meaning: "เครื่องดื่ม"}
    ],
    5: [
        {word: "accountant", type: "n.", meaning: "พนักงานบัญชี"},
        {word: "actor", type: "n.", meaning: "นักแสดงชาย"},
        {word: "actress", type: "n.", meaning: "นักแสดงหญิง"},
        {word: "adventure", type: "n.", meaning: "การผจญภัย"},
        {word: "appear", type: "v.", meaning: "ปรากฏ"},
        {word: "area", type: "n.", meaning: "พื้นที่ บริเวณ"},
        {word: "author", type: "n.", meaning: "นักเขียน, นักประพันธ์"},
        {word: "behind", type: "adv./prep.", meaning: "ข้างหลัง, ด้านหลัง"},
        {word: "blow", type: "v.", meaning: "พัด, เป่า,พ่น"},
        {word: "bridge", type: "n.", meaning: "สะพาน"}
    ],
    6: [
        {word: "advertisement", type: "n.", meaning: "การโฆษณา"},
        {word: "aeroplane", type: "n.", meaning: "เครื่องบิน"},
        {word: "afraid", type: "adj.", meaning: "กลัว"},
        {word: "ahead", type: "adj", meaning: "ข้างหน้า"},
        {word: "amusement", type: "n.", meaning: "สันทนาการ,ความสนุกสนาน"},
        {word: "ancient", type: "adj.", meaning: "เก่าแก่,โบราณ"},
        {word: "animate", type: "v.", meaning: "เคลื่อนไหว,มีชีวิต"},
        {word: "aquarium", type: "n.", meaning: "ตู้ปลา"},
        {word: "architect", type: "n.", meaning: "สถาปนิก"},
        {word: "arrange", type: "v.", meaning: "จัด,เตรียม"}
    ]
};